name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-versions: ${{ steps.gen.outputs.versions}}
    steps:
      - id: gen
        run: echo 'version=["1.24", "1.25"]' >> "$GITHUB_OUTPUT"
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install/Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Lint
        run: go vet ./...
  test:
    needs: setup
    strategy:
      matrix:
        go-version: ${{ fromJson(needs.setup.outputs.go-versions) }}
        os: [ubuntu-latest, macos-latest]
        exclude:
          - go-version: "1.24"
            os: macos-latest
        include:
          - go-version: "1.25"
            os: ubuntu-latest
            coverage: "true"
      fail-fast: false
      max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install/Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - run: go test -race -cover ./...
      - name: Create coverage report
        if: ${{ matrix.coverage == 'true' }}
        run: go test -race -cover -coverprofile=coverage.out ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install/Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Build
        run: go build ./...
      - name: Cache Go build
        if: ${{ runner.os == 'Linux'}}
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-gobuild-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuild-${{ matrix.go }}-
